### ISSUE TITLE
Pin settings in comment mixed up

### ISSUE THREAD

**Issue by oldroger** [BrentSeidel/BBS-BBB-Ada#4]
Hello Brent,

first of all - fine work you did - exactly what I was looking for.
There a small typo in the comments for PinMuxing in the comments within bbs-bbb-pins.ads.
Instead of 
--   EHRPWM1A: P9_14; -- or P8_34
--   EHRPWM1B: P9_16; -- or P8_36

it should be

--   EHRPWM1A: P9_14; -- or P8_36
--   EHRPWM1B: P9_16; -- or P8_34

Thanx and regards

Philipp

**Comment by BrentSeidel** [comment]
Should be corrected in commit 9b87f60b524911a28c5b169e6d6f48a3bbd9fa69, 05-Jun-2016.

**Comment by BrentSeidel** [comment]
Since there are no further comments on this, I will consider the issue closed.
Thanks,
Brent
